name: Test input triggers

on:
  workflow_dispatch:
    inputs:
      FileName:
        description: "To select the file"
        type: choice
        options:
          - test.txt
jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: File contents
        run: cat ${{ inputs.FileName }}

      # - name: demo runner context
      #   env: 
      #     RUNNER_CONTEXT: ${{ toJson(runner) }}
      #   run: echo "$RUNNER_CONTEXT"
