name: Test input triggers for test file

on:
  workflow_dispatch:
    inputs:
      FileName:
        description: "To select the file"
        type: choice
        options:
          - test.txt

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: File contents
        run: cat ${{ github.event.inputs.FileName }}

---

name: Test input trigger for README file

on:
  workflow_dispatch:
    inputs:
      FileName:
        description: "To select the file"
        type: choice
        options:
          - README.md

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: File contents
        run: cat ${{ github.event.inputs.FileName }}
