name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  run-hello-world:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Hello World
        run: echo "Hello, World!"

